# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: heimdall.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'heimdall.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eheimdall.proto\x12\x08heimdall\"K\n\x0cRobotPoseMsg\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\x0f\n\x07heading\x18\x03 \x01(\x02\x12\x14\n\x0ctimestamp_ns\x18\x04 \x01(\x04\"x\n\x10TrackedObjectMsg\x12\x10\n\x08track_id\x18\x01 \x01(\r\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\n\n\x02vx\x18\x05 \x01(\x02\x12\n\n\x02vy\x18\x06 \x01(\x02\x12\x12\n\nconfidence\x18\x07 \x01(\x02\"f\n\rTrackEventMsg\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.heimdall.TrackEventTypeMsg\x12*\n\x06object\x18\x02 \x01(\x0b\x32\x1a.heimdall.TrackedObjectMsg\"c\n\x11\x44\x65tectionFrameMsg\x12\'\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x17.heimdall.TrackEventMsg\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x04\x12\x0f\n\x07healthy\x18\x03 \x01(\x08\"\x84\x01\n\x0fRawDetectionMsg\x12\x11\n\tcamera_id\x18\x01 \x01(\x05\x12\x10\n\x08\x63lass_id\x18\x02 \x01(\x05\x12\x12\n\nconfidence\x18\x03 \x01(\x02\x12\x0c\n\x04left\x18\x04 \x01(\x02\x12\x0b\n\x03top\x18\x05 \x01(\x02\x12\r\n\x05width\x18\x06 \x01(\x02\x12\x0e\n\x06height\x18\x07 \x01(\x02\"[\n\x14RawDetectionFrameMsg\x12-\n\ndetections\x18\x01 \x03(\x0b\x32\x19.heimdall.RawDetectionMsg\x12\x14\n\x0ctimestamp_ns\x18\x02 \x01(\x04*9\n\x11TrackEventTypeMsg\x12\r\n\tCONFIRMED\x10\x00\x12\x0b\n\x07UPDATED\x10\x01\x12\x08\n\x04LOST\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'heimdall_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRACKEVENTTYPEMSG']._serialized_start=660
  _globals['_TRACKEVENTTYPEMSG']._serialized_end=717
  _globals['_ROBOTPOSEMSG']._serialized_start=28
  _globals['_ROBOTPOSEMSG']._serialized_end=103
  _globals['_TRACKEDOBJECTMSG']._serialized_start=105
  _globals['_TRACKEDOBJECTMSG']._serialized_end=225
  _globals['_TRACKEVENTMSG']._serialized_start=227
  _globals['_TRACKEVENTMSG']._serialized_end=329
  _globals['_DETECTIONFRAMEMSG']._serialized_start=331
  _globals['_DETECTIONFRAMEMSG']._serialized_end=430
  _globals['_RAWDETECTIONMSG']._serialized_start=433
  _globals['_RAWDETECTIONMSG']._serialized_end=565
  _globals['_RAWDETECTIONFRAMEMSG']._serialized_start=567
  _globals['_RAWDETECTIONFRAMEMSG']._serialized_end=658
# @@protoc_insertion_point(module_scope)
